name: 'Security Report'
description: 'Report a security vulnerability'
title: '[SECURITY] '
labels: security

body:
  - type: markdown
    attributes:
      value: |
        Fill out the sections below to help us reproduce and fix the vulnerability.
        Please ensure you are using the latest version of the library before reporting.
        Fill in as much of the template below as you're able. The more you include, the easier it will be to reproduce and fix the vulnerability.

  - type: input
    id: description
    attributes:
      label: 'Description'
      description: 'Please describe the vulnerability in detail.'
      placeholder: 'Describe the vulnerability here'
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Demonstrate
      description: Write step by step instructions to demonstrate the vulnerability.
      placeholder: |
        Steps to demonstrate the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
      placeholder: Steps to reproduce the bug
    validations:
      required: true

  - type: input
    id: impact
    attributes:
      label: 'Impact'
      description: 'What is the potential impact of this vulnerability?'
      placeholder: Large scale

  - type: textarea
    id: resources
    attributes:
      label: Online Resources
      description: |
        Add any online resources that can help us understand the vulnerability better.
        Add links to blog posts, articles, or other resources.
      placeholder: |
        The blogs describing why this practice creates security vulnerabilities:
        - [Example](https://example.com)
        - [Another Example](https://example.com)

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Please specify the browser you are using with its version (e.g., Chrome, Safari).
      placeholder: Chrome - Version 132.0.6834.83/84
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Please specify the version of the library you are using (e.g., 1.1.0).
      placeholder: v1.1.0
    validations:
      required: true

  - type: textarea
    id: additional_environment
    attributes:
      label: Additional Environment Information
      description: Add any other relevant environment information here.
      render: bash
      placeholder: |
        Operating System:
          Platform: darwin
          Arch: arm64
          Version: Darwin Kernel Version 23.6.0
        Binaries:
          Node: 20.17.0
          npm: 10.8.2
          Yarn: 1.22.22

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here.
        Add screenshots if applicable.
      placeholder: |
        Additional context
        Attaching a screenshot of the issue would be helpful.
