name: Bug report
description: Report a bug to help us improve
title: '[BUG] '
labels: bug
type: bug

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id:
    attributes:
      label: Link to the code that reproduces this issue
      description: |
        Please provide a link to a **public** repository on GitHub or codesandbox that contains the code that reproduces the issue.
      placeholder: 'https://github.com/your-username/your-repo'

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      placeholder: Steps to reproduce the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Expected behavior

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened.
      placeholder: Actual behavior

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Please specify the browser you are using with its version (e.g., Chrome, Safari).
      placeholder: Browser
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Please specify the version of the library you are using (e.g., 1.1.0).
      placeholder: Version
    validations:
      required: true

  - type: textarea
    id: additional_environment
    attributes:
      label: Additional Environment Information
      description: Add any other relevant environment information here.
      placeholder: Additional environment information

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Additional context
