name: 'Security Report'
description: 'Report a security vulnerability'
title: '[SECURITY] '
labels: security

body:
  - type: markdown
    attributes:
      value: |
        Fill out the sections below to help us reproduce and fix the vulnerability.
        Please ensure you are using the latest version of the library before reporting.
        Fill in as much of the template below as you're able. The more you include, the easier it will be to reproduce and fix the vulnerability.

  - type: input
    id: description
    attributes:
      label: 'Description'
      description: 'Please describe the vulnerability in detail.'
      placeholder: 'Describe the vulnerability here'
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: 'Steps to Reproduce'
      description: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      placeholder: Steps to reproduce the bug
    validations:
      required: true

  - type: input
    id: impact
    attributes:
      label: 'Impact'
      description: 'What is the potential impact of this vulnerability?'
      placeholder: 'Describe the impact here'

  - type: textarea
    id: resources
    attributes:
      label: Online Resources
      description: |
        Add any online resources that can help us understand the vulnerability better.
        Add links to blog posts, articles, or other resources.
      placeholder: Links to online resources

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Please specify the browsers this vulnerability will impact (e.g., Chrome, Safari).
      placeholder: Browser
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Please specify the version of the library having the vulnerability (e.g., 1.1.0).
      placeholder: Version
    validations:
      required: true

  - type: textarea
    id: additional_environment
    attributes:
      label: Additional Environment Information
      description: Add any other relevant environment information here.
      placeholder: Additional environment information

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here.
        Add screenshots if applicable.
      placeholder: Additional context
