# This workflow will build the Storybook documentation whenever a new release branch is created

name: Build Version Docs

on:
  release:
    types: [published]

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Setup git
        run: |
          git config --global user.name 'Github Bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
      - name: Setup gh-pages branch
        run: |
          git fetch origin
          git checkout master
          git checkout gh-pages
          git merge master --allow-unrelated-histories --no-edit
      - name: Install dependencies
        run: npm ci
      - name: Build storybook docs
        run: npm run build-version-docs ${{ github.event.release.tag_name }}
      - name: Commit and push changes
        run: |
          git add docs/${{ github.event.release.tag_name }} -f
          git commit --allow-empty -m "[BOT] Build Storybook"
          git push origin gh-pages
