# This workflow will push the latest code to a different branch when a release is created

name: Create Release Branch

on:
  release:
    types: [published]

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create and push branch
        env:
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
        run: |
          git config --global user.name 'Github Bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          git checkout -B "release-$RELEASE_VERSION"
          git push -u origin "release-$RELEASE_VERSION" --force
